const actionTypes = {
  LOGIN_USER: "LOGIN_USER",
  USER_STATE: "USER_STATE",
  LOGOUT_USER: "LOGOUT_USER",
  USER_INFO: "USER_INFO",
  STORY_NOTIFICATION: "STORY_NOTIFICATION",
  COMMENT_NOTIFICATION: "COMMENT_NOTIFICATION",
};

export default actionTypes;
